export const storeProducts = [
    {
        id: 1,
        title: "Space Cat Sock",
        img: "img/socks1.jpg",
        price: 29,
        info: "Add a little (solar) flair to your wardrobe with the Space Cat low sock. It won’t go near water, but the infinite, ever-expanding void we call the universe is a doddle when you’re Space Cat.",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Bavaria Duck Sock",
        img: "img/socks2.jpg",
        price: 39,
        info: "Prepare for the wurst! The duck is back, now with a background with the traditional bavarian motif perfectly fitting any Oktoberfest feast!",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Stripe Sock",
        img: "img/socks3.jpg",
        price: 19,
        info: "It’s the classic Stripe sock style! And we think your wardrobe would definitely stop secretly crying in its car if you would just go out and buy it a pair",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Filled Optic Sock",
        img: "img/socks4.jpg",
        price: 29,
        info: "Make a proper entrance! The Filled Optic sock has a hypnotic cuboid design – guaranteed to mesmerise anyone who stares too long. Be sure to use your powers only for good and not for evil. Just kidding. Go fetch Carol and get her to marry her shoe or something.",
        inCart: false,
        sizes: "S M",
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Cherry Dog Sock",
        img: "img/socks5.jpg",
        price: 29,
        info: "Never lick a dog. Lick a Cherry Dog instead! We highly encourage it. (It actually tastes like pomegranate). It’s delicious and weird and utterly adorable. The Cherry Dog sock will be the sweetest companion to any outfit.",
        inCart: false,
        sizes: "M L",
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Big Dot Sock",
        img: "img/socks6.jpg",
        price: 29,
        info: "Whatever you’re doing, do it in your Big Dot sock. One of our first Happy Socks styles, this fresh and happy pattern has been in pretty much every collection since 2008. Worry not, it’s not going anywhere.",
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: "Clean Elephant Sock",
        img: "img/socks7.jpg",
        price: 29,
        info: "Wash away bad days and grey moods with the Clean Elephant sock. This colorful, fun-filled design is a big foamy bubble bath made for the soul (or soles?) Anyone?",
        inCart: false,
        sizes: "S M",
        count: 0,
        total: 0
    },
    {
        id: 8,
        title: "Red Dots Sock",
        img: "img/socks8.png",
        price: 19,
        info: "Is this just another sock with dots on it? Or a physical representation of the neverending state of the universe and all the mysteries it contains within it? Nope, it’s just dots, sorry.",
        inCart: false,
        sizes: "S M",
        count: 0,
        total: 0
    },
    {
        id: 9,
        title: "Masquerade Sock",
        img: "img/socks9.png",
        price: 19,
        info: "Who’s that? Who cares–it’s a masquerade. The reason why Carnival season is so much fun is that you can party on equal terms, behind a mask. Now you don’t need one to create a mysterious look. The blue Masquerade Sock is all you need.",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 10,
        title: "Crazy Dot Sock",
        img: "img/socks10.png",
        price: 29,
        info: "It’s (almost) impossible to resist the green and pink Crazy Dot socks. Somewhere between a cinnamon bun and a surreal dartboard, this original print is made to mesmerize.",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 11,
        title: "SpongeBob Sock",
        img: "img/socks11.jpg",
        price: 39,
        info: "Step into SpongeBob’s wonderful world in the special edition Say Cheese socks. The legendary Krabby Patty gets a bubble-shaped makeover in this delicious yellow and blue design.",
        inCart: false,
        sizes: "L",
        count: 0,
        total: 0
    },
    {
        id: 12,
        title: "Circle Of Friends Sock",
        img: "img/socks12.jpg",
        price: 29,
        info: "Step into SpongeBob’s wonderful world in the special edition Circle of Friends socks. The black and yellow style combines the familiar faces of his closest friends with the iconic Big Dot-pattern.",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 13,
        title: "Stripe Sock",
        img: "img/socks13.jpg",
        price: 29,
        info: "Never has a pair of socks been more essential than our Stripe Low socks. These comfy, combed cotton socks are lower than our regular pairs, so they're ideal for wearing with sneakers or casual outfits. Muted rainbow stripes in shades of khaki, golden yellow, teal, plum, light plum, lilac and coral pink and contrasted by a color-block coral pink toe and heel. Available in men's and women's sizes.",
        inCart: false,
        sizes: "S M",
        count: 0,
        total: 0
    },
    {
        id: 14,
        title: "Rubber Duck Sock",
        img: "img/socks14.jpg",
        price: 39,
        info: "Look cooler than cool in Rubber Duck socks. Featuring your favorite bath-time buddy in shades, this cheerful design will have you smiling all day long. (Unless your of course you’re too cool for that). Made from combed cotton in sizes for men and women.",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 15,
        title: "Flamingo Sock",
        img: "img/socks15.jpg",
        price: 19,
        info: "Can a flock stand out? Of course! Flash your most colorful self with the black Flamingo socks. Tall and proud, these colorful characters brighten up your everyday and outfit.",
        inCart: false,
        sizes: "S M",
        count: 0,
        total: 0
    },
    {
        id: 16,
        title: "Popcorn Sock",
        img: "img/socks16.jpg",
        price: 29,
        info: "It’s understandable if you don’t want to share this crunchy pair of Popcorn socks. This refreshing blue and red pair is every movie lover's dream and will light brighten up your everyday.",
        inCart: false,
        sizes: "M L",
        count: 0,
        total: 0
    },
    {
        id: 17,
        title: "Sunny Side Up Sock",
        img: "img/socks17.jpg",
        price: 19,
        info: "Start the day off with a smile! These Sunny Side Up socks in navy have a fun fried egg pattern, bringing you good vibes and sunny weather – whatever the season or side of the bed you wake up on. Made from combed cotton. Available in sizes for men and women.",
        inCart: false,
        sizes: "M L",
        count: 0,
        total: 0
    },
    {
        id: 18,
        title: "Dot Liner Sock",
        img: "img/socks18.jpg",
        price: 19,
        info: "Keep it cool all summer long with Dot Liner socks. Full of polka dots in vibrant shades, this white, blue and red no-show pair of socks is a colorful treat that only you know about. Slip on a pair when the weather is warm or when you really want to highlight your sneakers. Crafted from combed cotton in unisex sizes.",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 19,
        title: "Banana Sock",
        img: "img/socks19.jpg",
        price: 39,
        info: "Who can say no to a pair of Banana socks? The half moon-like curves in yellow and blue can be enjoyed as it is, or maybe you combine it with another design for a fruit salad style.",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
    {
        id: 20,
        title: "Athletic Crew Sock",
        img: "img/socks20.jpg",
        price: 39,
        info: "Happy? Show it in the Athletic Happy 3/4 crew socks in black and red. The new, shorter length crew style is perfect for when the temperatures rise but you want to stay cool.",
        inCart: false,
        sizes: "S M L",
        count: 0,
        total: 0
    },
]